version: "3.3"
services:
  symfony:
    image: udaysh/alpine_php:latest
    labels:
      - "com.lowecloud.proxy=symfony.docker"
    volumes:
      - "./app:/app"
    network_mode: bridge
    links:
      - db

  db:
    image: udaysh/db_mariadb-10
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - "com.lowecloud.proxy=symfony_db.docker"
    ports:
      - "3340:3306"
    network_mode: bridge